import 'package:recolle/features/favorites/models/favorite_artist.dart';
import 'package:recolle/features/records/models/record.dart';

/// デモモード（スクリーンショット撮影用）の記録。
///
/// 日付は [now] からの相対で決めるので、いつ撮っても「これから」の公演が先頭に並ぶ。
List<Record> demoRecords(DateTime now) {
  DateTime day(int offset) => DateTime(now.year, now.month, now.day + offset);

  return [
    // これから
    Record(
      id: 'demo-live-next-1',
      type: RecordType.live,
      title: 'YOASOBI ARENA TOUR 2026',
      artistOrAuthor: 'YOASOBI',
      date: day(9),
      venue: 'さいたまスーパーアリーナ',
      ticketSource: 'ファンクラブ',
      seat: 'アリーナ B 12 ブロック',
      ticketPrice: 9800,
      openTime: const ClockTime(17, 0),
      startTime: const ClockTime(18, 0),
    ),
    Record(
      id: 'demo-live-next-2',
      type: RecordType.live,
      title: 'Aimer Live Tour "Blue Hour"',
      artistOrAuthor: 'Aimer',
      date: day(24),
      venue: '日本武道館',
      ticketSource: 'e+',
      ticketPrice: 8800,
      openTime: const ClockTime(17, 30),
      startTime: const ClockTime(18, 30),
    ),
    Record(
      id: 'demo-live-next-3',
      type: RecordType.live,
      title: 'Official髭男dism ONE-MAN LIVE',
      artistOrAuthor: 'Official髭男dism',
      date: day(52),
      venue: '横浜アリーナ',
      ticketSource: 'ローチケ',
      ticketPrice: 9500,
      openTime: const ClockTime(17, 0),
      startTime: const ClockTime(18, 0),
    ),
    Record(
      id: 'demo-movie-next',
      type: RecordType.movie,
      title: 'ハウルの動く城',
      artistOrAuthor: '宮崎駿',
      date: day(5),
      venue: 'TOHOシネマズ 新宿',
      ticketSource: 'ムビチケ',
      ticketPrice: 1900,
      startTime: const ClockTime(19, 10),
    ),

    // 過去のライブ
    Record(
      id: 'demo-live-1',
      type: RecordType.live,
      title: 'King Gnu Dome Tour 2026',
      artistOrAuthor: 'King Gnu',
      date: day(-12),
      venue: '東京ドーム',
      ticketSource: 'ファンクラブ',
      seat: 'スタンド 3 塁側 22 通路 14 列',
      ticketPrice: 10500,
      openTime: const ClockTime(16, 30),
      startTime: const ClockTime(18, 0),
      endTime: const ClockTime(20, 40),
      setlist: [
        'どろん',
        '白日',
        'Teenager Forever',
        'Slumberland',
        'BOY',
        'Vinyl',
        'Prayer X',
        'Stardom',
        '--- アンコール ---',
        '一途',
        'SPECIALZ',
      ].join('\n'),
      mcMemo: '「東京ドーム、帰ってきました」の一言で会場が揺れた。',
      impressions: 'アンコールの一途で鳥肌が立った。花道のすぐ近くで、表情まで見えた。',
    ),
    Record(
      id: 'demo-live-2',
      type: RecordType.live,
      title: '藤井 風 LOVE ALL ARENA TOUR',
      artistOrAuthor: '藤井 風',
      date: day(-27),
      venue: '大阪城ホール',
      ticketSource: 'e+',
      seat: '2 階 北 5 列',
      ticketPrice: 9900,
      openTime: const ClockTime(17, 0),
      startTime: const ClockTime(18, 0),
      endTime: const ClockTime(20, 30),
      setlist: [
        'ガーデン',
        'きらり',
        'まつり',
        '満ちてゆく',
        '何なんw',
        '花',
        '--- アンコール ---',
        'grace',
      ].join('\n'),
      impressions: 'ピアノの弾き語りだけで、会場の空気が変わった。',
    ),
    Record(
      id: 'demo-live-3',
      type: RecordType.live,
      title: 'back number stadium live',
      artistOrAuthor: 'back number',
      date: day(-45),
      venue: '福岡PayPayドーム',
      ticketSource: 'ファンクラブ',
      ticketPrice: 9800,
      openTime: const ClockTime(15, 30),
      startTime: const ClockTime(17, 0),
      setlist: ['水平線', '花束', 'ヒロイン', 'クリスマスソング', '高嶺の花子さん'].join('\n'),
      impressions: '水平線で、ドーム全体が青く染まった。一生忘れない夜。',
    ),
    Record(
      id: 'demo-live-4',
      type: RecordType.live,
      title: 'Ado WORLD TOUR 2026',
      artistOrAuthor: 'Ado',
      date: day(-70),
      venue: '幕張メッセ',
      ticketSource: 'ローチケ',
      seat: 'アリーナ スタンディング',
      ticketPrice: 12000,
      openTime: const ClockTime(17, 0),
      startTime: const ClockTime(18, 0),
      setlist: ['新時代', 'うっせぇわ', '踊', 'ウタカタララバイ', '唱', 'readymade'].join('\n'),
      impressions: '生歌の迫力が想像以上。音圧で胸が震えた。',
    ),
    Record(
      id: 'demo-live-5',
      type: RecordType.live,
      title: 'Mrs. GREEN APPLE ARENA TOUR',
      artistOrAuthor: 'Mrs. GREEN APPLE',
      date: day(-96),
      venue: '横浜アリーナ',
      ticketSource: 'チケットぴあ',
      ticketPrice: 9500,
      openTime: const ClockTime(17, 0),
      startTime: const ClockTime(18, 0),
      setlist: ['ケセラセラ', 'ライラック', 'ダンスホール', 'ロマンチシズム', 'インフェルノ'].join('\n'),
      impressions: '色とりどりの演出が楽しすぎて、あっという間だった。',
    ),
    Record(
      id: 'demo-live-6',
      type: RecordType.live,
      title: '星野源 DOME TOUR',
      artistOrAuthor: '星野源',
      date: day(-130),
      venue: '京セラドーム大阪',
      ticketSource: 'ファンクラブ',
      ticketPrice: 9800,
      openTime: const ClockTime(16, 0),
      startTime: const ClockTime(17, 30),
      setlist: ['恋', 'SUN', '創造', 'ドラえもん', '不思議'].join('\n'),
      impressions: '恋ダンスを会場全員で踊った。最高に楽しい時間。',
    ),
    Record(
      id: 'demo-live-7',
      type: RecordType.live,
      title: 'Official髭男dism Hall Tour',
      artistOrAuthor: 'Official髭男dism',
      date: day(-170),
      venue: 'NHKホール',
      ticketSource: 'e+',
      ticketPrice: 8800,
      startTime: const ClockTime(18, 0),
      setlist: [
        'Pretender',
        'I LOVE...',
        'Subtitle',
        'Cry Baby',
        'ノーダウト',
      ].join('\n'),
      impressions: 'ホールならではの音の良さ。ボーカルが一音一音まで届いた。',
    ),

    // 対バン
    Record(
      id: 'demo-taiban-1',
      type: RecordType.live,
      title: 'TWO-MAN LIVE "GOLDEN HOUR"',
      artistOrAuthor: 'Aimer ／ Ado',
      date: day(-60),
      venue: 'Zepp Haneda',
      ticketSource: 'e+',
      ticketPrice: 7000,
      openTime: const ClockTime(17, 30),
      startTime: const ClockTime(18, 30),
      eventFormat: EventFormat.taiban,
      acts: const [
        RecordAct(
          artist: 'Aimer',
          isMain: true,
          songs: ['カタオモイ', '蝋燭', 'Brave Shine', 'RE:far'],
        ),
        RecordAct(
          artist: 'Ado',
          isMain: true,
          songs: ['うっせぇわ', '阿修羅ちゃん', 'ギラギラ'],
        ),
      ],
      impressions: '好きな 2 組を同じ日に観られて、夢みたいな夜だった。',
    ),

    // フェス（複数日）
    Record(
      id: 'demo-fes-1',
      type: RecordType.live,
      title: 'SUMMER SONIC 2026',
      artistOrAuthor: 'Mrs. GREEN APPLE',
      date: day(-55),
      endDate: day(-54),
      venue: '幕張メッセ',
      ticketSource: 'チケットぴあ',
      ticketPrice: 32000,
      eventFormat: EventFormat.festival,
      acts: const [
        RecordAct(
          artist: 'Mrs. GREEN APPLE',
          isMain: true,
          day: 1,
          songs: ['ケセラセラ', 'ライラック', 'インフェルノ'],
        ),
        RecordAct(artist: 'King Gnu', day: 1, songs: ['白日', 'SPECIALZ']),
        RecordAct(artist: 'YOASOBI', day: 2, songs: ['アイドル', '夜に駆ける', '群青']),
      ],
      impressions: '2 日間、ずっと音の中にいた。夕焼けの中のライラックが忘れられない。',
    ),

    // 映画
    Record(
      id: 'demo-movie-1',
      type: RecordType.movie,
      title: '君の名は。',
      artistOrAuthor: '新海誠',
      date: day(-8),
      venue: 'TOHOシネマズ 新宿',
      ticketSource: 'ムビチケ',
      ticketPrice: 1900,
      startTime: const ClockTime(19, 0),
      impressions: '何度観ても、ラストのシーンで泣いてしまう。',
    ),
    Record(
      id: 'demo-movie-2',
      type: RecordType.movie,
      title: '千と千尋の神隠し',
      artistOrAuthor: '宮崎駿',
      date: day(-38),
      venue: '109シネマズ 湘南',
      ticketSource: '劇場窓口',
      ticketPrice: 1800,
      startTime: const ClockTime(13, 30),
      impressions: '大きなスクリーンで観られて幸せだった。',
    ),
    Record(
      id: 'demo-movie-3',
      type: RecordType.movie,
      title: 'すずめの戸締まり',
      artistOrAuthor: '新海誠',
      date: day(-100),
      venue: 'ユナイテッド・シネマ 豊洲',
      ticketSource: '劇場のサイト・アプリ',
      ticketPrice: 1900,
      startTime: const ClockTime(16, 40),
    ),

    // 本
    Record(
      id: 'demo-book-1',
      type: RecordType.book,
      title: '成瀬は天下を取りにいく',
      artistOrAuthor: '宮島未奈',
      date: day(-15),
      ticketSource: '書店',
      ticketPrice: 1650,
      impressions: '成瀬の真っすぐさに元気をもらえた。',
    ),
    Record(
      id: 'demo-book-2',
      type: RecordType.book,
      title: 'コンビニ人間',
      artistOrAuthor: '村田沙耶香',
      date: day(-82),
      ticketSource: '電子書籍',
      ticketPrice: 726,
    ),

    // その他
    Record(
      id: 'demo-other-1',
      type: RecordType.other,
      title: '東京都現代美術館 企画展',
      artistOrAuthor: '',
      date: day(-20),
      venue: '東京都現代美術館',
      ticketSource: '当日券',
      ticketPrice: 2000,
      impressions: '光の作品が特に印象的で、しばらく動けなかった。',
    ),
    Record(
      id: 'demo-other-2',
      type: RecordType.other,
      title: '劇団四季 ライオンキング',
      artistOrAuthor: '',
      date: day(-110),
      venue: '四季劇場 [春]',
      ticketSource: '公式サイト',
      ticketPrice: 11000,
      startTime: const ClockTime(13, 0),
    ),
  ];
}

/// デモモードのお気に入りのアーティスト。
List<FavoriteArtist> demoFavorites(DateTime now) => [
  for (final (i, name) in [
    'YOASOBI',
    'Aimer',
    'King Gnu',
    'Official髭男dism',
    'Mrs. GREEN APPLE',
    'Ado',
    '藤井 風',
    'back number',
  ].indexed)
    FavoriteArtist(
      id: 'demo-fav-$i',
      name: name,
      createdAt: now.subtract(Duration(days: 200 - i * 10)),
    ),
];
